-- Create sequences for ID generation
CREATE SEQUENCE terem_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE foglalas_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE esemeny_tipus_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE tanar_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE kurzus_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE kurzus_terem_seq START WITH 1 INCREMENT BY 1;
CREATE SEQUENCE foglalas_tanar_seq START WITH 1 INCREMENT BY 1;
